name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.61.0
          skip-pkg-cache: true
          args: '--out-format=colored-line-number --disable-all --enable=gofmt --enable=govet --enable=revive pm verification'
